### ISSUE TITLE
Not working with latest version

### ISSUE THREAD

**Issue by Amadeus-** [Albeoris/AtomRPG.NuclearEdition#1]
This mod does not seem to be working with the latest version of ATOM RPG.    The game doesn't load at all with it installed -- so, perhaps it's the version of UnityEngine.CoreModule.dll that's included?

Thanks!

**Comment by Albeoris** [comment]
**Fixed:**
https://github.com/Albeoris/AtomRPG.NuclearEdition/releases/tag/v2019.10.02

Unpack to the %appdata%\..\LocalLow\AtomTeam\Atom\Mods
